title: Sofia F. Zarate # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Hi! I hope you are well. I’m Sofi, a veterinarian and university assistant professor who became a Data Analyst. 
  <br><br>
  I find my experience as a veterinarian, assistant professor and researcher to be an advantage when it comes to thinking logically, analyzing big data and solving problems judiciously. My main interest is to continue training as a Machine Learning Specialist.
  <br><br>
  <a href="https://www.linkedin.com/in/sofiafzarate">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
