title: Sofia F. Zarate # your name (or website title) here
logo: "/images/foto cv 02.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Hi! I hope you are well. I’m Sofi, Data Analyst with 2+ years of experience in the industry. I'm currently employed in a fintech and I freelance as a sidejob. 
  <br><br>
  I started my proffesional journey as a veterinarian, assistant professor and researcher. I find my past experience to be an advantage when it comes to thinking logically, analyzing big data and solving problems judiciously.
  <br><br>
  <a href="https://www.linkedin.com/in/sofiafzarate">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 
# your Google Analytics tracking ID here
